name: Get Deno Version

on:
  workflow_call:
    outputs:
      version:
        description: The Deno version from .dvmrc
        value: ${{ jobs.get-deno-version.outputs.version }}

jobs:
  get-deno-version:
    name: Get Deno Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.deno-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: .dvmrc
          sparse-checkout-cone-mode: false
      - id: deno-version
        run: echo "version=$(cat .dvmrc)" >> $GITHUB_OUTPUT
