name: Publish

on:
  release:
    types: [published]

jobs:
  decipher:
    name: Decipher
    runs-on: ubuntu-latest
    outputs:
      package: ${{ fromJSON(steps.tag.outputs.groups).package }}
      version: ${{ fromJSON(steps.tag.outputs.groups).version }}
    steps:
      - name: Tag
        id: tag
        uses: johngeorgewright/regex-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          regex: ^refs/tags/(?P<package>@target/[a-zA-Z0-9_-]+)-v(?P<version>\d+.\d+.\d+)$

  npm:
    name: NPM
    runs-on: ubuntu-latest
    needs: [decipher]
    if: needs.decipher.outputs.package != '' && needs.decipher.outputs.version != ''
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Get Node Version from NVM
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup
        run: |
          yarn config set npmPublishRegistry https://registry.npmjs.org
          yarn config set npmAuthToken $NPM_TOKEN
          yarn --immutable
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: yarn workspace ${{ needs.decipher.outputs.package }} build

      - name: Publish
        run: yarn workspace ${{ needs.decipher.outputs.package }} npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
