name: Pull Request

on:
  pull_request:
  workflow_call:

jobs:
  get-deno-version:
    uses: ./.github/workflows/get-deno-version.yml

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: get-deno-version
    container:
      image: denoland/deno:${{ needs.get-deno-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - run: deno check --frozen
      - run: deno lint
      - run: deno task test
